import type { RailLine, Segment, Station } from "./types";

export const stations: Station[] = [
  { id: "shibuya", name: "渋谷", nameEn: "Shibuya", x: 420, y: 210, display: { isMajor: true, isTransfer: true, priority: 100 } },
  { id: "omote-sando", name: "表参道", nameEn: "Omote-sando", x: 490, y: 205, display: { isTransfer: true, priority: 70 } },
  { id: "aoyama-itchome", name: "青山一丁目", nameEn: "Aoyama-itchome", x: 560, y: 200, display: { isTransfer: true, priority: 62 } },
  { id: "nagatacho", name: "永田町", nameEn: "Nagatacho", x: 630, y: 195, display: { isTransfer: true, priority: 68 } },
  { id: "otemachi", name: "大手町", nameEn: "Otemachi", x: 720, y: 185, display: { isMajor: true, isTransfer: true, priority: 88 } },
  { id: "oshiage", name: "押上", nameEn: "Oshiage", x: 835, y: 150, display: { isTransfer: true, priority: 60 } },
  { id: "sangen-jaya", name: "三軒茶屋", nameEn: "Sangen-jaya", x: 340, y: 250, display: { priority: 44 } },
  { id: "futako-tamagawa", name: "二子玉川", nameEn: "Futako-tamagawa", x: 235, y: 315, display: { isTransfer: true, priority: 64 } },
  { id: "mizonokuchi", name: "溝の口", nameEn: "Mizonokuchi", x: 160, y: 370, display: { isTransfer: true, priority: 76 } },
  { id: "machida", name: "南町田", nameEn: "Minami-machida", x: 80, y: 445, display: { priority: 36 } },
  { id: "shinjuku", name: "新宿", nameEn: "Shinjuku", x: 420, y: 115, display: { isMajor: true, isTransfer: true, priority: 96 } },
  { id: "ikebukuro", name: "池袋", nameEn: "Ikebukuro", x: 515, y: 70, display: { isMajor: true, isTransfer: true, priority: 92 } },
  { id: "ueno", name: "上野", nameEn: "Ueno", x: 690, y: 95, display: { isMajor: true, isTransfer: true, priority: 84 } },
  { id: "tokyo", name: "東京", nameEn: "Tokyo", x: 720, y: 230, display: { isMajor: true, isTransfer: true, priority: 100 } },
  { id: "shinagawa", name: "品川", nameEn: "Shinagawa", x: 570, y: 340, display: { isMajor: true, isTransfer: true, priority: 90 } },
  { id: "meguro", name: "目黒", nameEn: "Meguro", x: 470, y: 330, display: { isTransfer: true, priority: 64 } },
  { id: "osaki", name: "大崎", nameEn: "Osaki", x: 535, y: 380, display: { isTransfer: true, priority: 58 } },
  { id: "kawasaki", name: "川崎", nameEn: "Kawasaki", x: 450, y: 475, display: { isMajor: true, isTransfer: true, priority: 82 } },
  { id: "musashi-kosugi", name: "武蔵小杉", nameEn: "Musashi-kosugi", x: 355, y: 425, display: { isMajor: true, isTransfer: true, priority: 86 } },
  { id: "noborito", name: "登戸", nameEn: "Noborito", x: 260, y: 380, display: { isTransfer: true, priority: 62 } },
  { id: "tachikawa", name: "立川", nameEn: "Tachikawa", x: 90, y: 310, display: { isMajor: true, isTransfer: true, priority: 78 } },
  { id: "yokohama", name: "横浜", nameEn: "Yokohama", x: 375, y: 555, display: { isMajor: true, isTransfer: true, priority: 94 } },
  { id: "ofuna", name: "大船", nameEn: "Ofuna", x: 285, y: 655, display: { isTransfer: true, priority: 70 } },
  { id: "kamakura", name: "鎌倉", nameEn: "Kamakura", x: 220, y: 705, display: { priority: 50 } },
];

export const lines: RailLine[] = [
  {
    id: "denentoshi",
    name: "東急田園都市線",
    operator: "Tokyu",
    color: "#20a288",
    display: { importance: 74 },
    stationIds: [
      "shibuya",
      "sangen-jaya",
      "futako-tamagawa",
      "mizonokuchi",
      "machida",
    ],
  },
  {
    id: "hanzomon",
    name: "東京メトロ半蔵門線",
    operator: "Tokyo Metro",
    color: "#8f76d6",
    display: { importance: 80 },
    stationIds: [
      "shibuya",
      "omote-sando",
      "aoyama-itchome",
      "nagatacho",
      "otemachi",
      "oshiage",
    ],
  },
  {
    id: "yamanote",
    name: "JR山手線",
    operator: "JR East",
    color: "#9acd32",
    display: { importance: 100 },
    stationIds: [
      "shibuya",
      "shinjuku",
      "ikebukuro",
      "ueno",
      "tokyo",
      "shinagawa",
      "osaki",
      "meguro",
      "shibuya",
    ],
  },
  {
    id: "nambu",
    name: "JR南武線",
    operator: "JR East",
    color: "#ffd400",
    display: { importance: 70 },
    stationIds: [
      "kawasaki",
      "musashi-kosugi",
      "mizonokuchi",
      "noborito",
      "tachikawa",
    ],
  },
  {
    id: "yokosuka",
    name: "横須賀線",
    operator: "JR East",
    color: "#007ac0",
    display: { importance: 82 },
    stationIds: [
      "tokyo",
      "shinagawa",
      "musashi-kosugi",
      "yokohama",
      "ofuna",
      "kamakura",
    ],
  },
];

export const segments: Segment[] = lines.flatMap((line) =>
  line.stationIds.slice(0, -1).map((stationId, index) => ({
    id: `${line.id}-${stationId}-${line.stationIds[index + 1]}`,
    lineId: line.id,
    fromStationId: stationId,
    toStationId: line.stationIds[index + 1],
  })),
);
